### ISSUE TITLE
can I setting firestoreSettings credential with admin.credential.cert

### ISSUE THREAD

**Issue by itoon** [glebbash/nestjs-fireorm#4]
I try to setup and got error

[Nest] 29478  - 04/08/2022, 1:11:42 AM   ERROR [ExceptionsHandler] Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.

Do you have any suggestion?
Thx

**Comment by glebbash** [comment]
If you are authorized using gcloud locally try to remove this line: https://github.com/glebbash/nestjs-fireorm/blob/f3e261caaceedd051dc6580307d77f96bcb2b331/example/src/app.module.ts#L10

Otherwise follow this guide on how to use service account credentials: https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable
